# Generated by Django 4.2.1 on 2023-06-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loanlist",
            fields=[
                ("l_no", models.AutoField(primary_key=True, serialize=False)),
                ("l_book_no", models.IntegerField()),
                ("l_m_id", models.CharField(max_length=50)),
                ("l_regdate", models.DateTimeField(blank=True, null=True)),
                ("l_returndate", models.DateTimeField(blank=True, null=True)),
                ("l_status", models.IntegerField(blank=True, null=True)),
                ("l_deley", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "loanlist",
                "managed": False,
            },
        ),
    ]
